**1) สร้าง vector, matrix**

In [0]:
import numpy as np
from IPython.display import display

สร้าง vector (array 1 มิติ)

In [0]:
a=np.array([1,2,3],dtype='int8')
a

array([1, 2, 3], dtype=int8)

เช็ค dimension ของ array

In [0]:
a.shape

(3,)

สร้าง matrix (array หลาย มิติ)

In [0]:
b=np.array([[1,2,3],[4,5,6]],dtype='float64')
b

array([[1., 2., 3.],
       [4., 5., 6.]])

เช็ค dimension ของ matrix

In [0]:
b.shape

(2, 3)

คำสั่งเรียก array พิเศษบางชนิดที่น่าสนใจ

In [0]:
display(np.ones([3,3])); display(np.zeros([3,3]))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**2) Indexing**

In [0]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ระบุ dimension เดียว

In [0]:
display(a[0]); display(a[-1])

array([1, 2, 3])

array([7, 8, 9])

ระบุ 2 dimension

In [0]:
display(a[1,1]); display(a[-1,-1])

5

9

ระบุ index โดยใช้ '':''

In [0]:
display(a[1:,:]); display(a[:,:-1])

array([[4, 5, 6],
       [7, 8, 9]])

array([[1, 2],
       [4, 5],
       [7, 8]])

ระบุหลาย index

In [0]:
display(a[[1,-1],:]); display(a[:,[1,-1]])

array([[4, 5, 6],
       [7, 8, 9]])

array([[2, 3],
       [5, 6],
       [8, 9]])

**3) Operation บวก, ลบ, คูณ, หาร**

In [0]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [0]:
b=np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

operation ระหว่าง array กับ array ที่ dimension เหมือนกัน

In [0]:
display(a+b); display(a-b); display(a*b); display(a/b)

array([[ 6,  8],
       [10, 12]])

array([[-4, -4],
       [-4, -4]])

array([[ 5, 12],
       [21, 32]])

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

operation ระหว่าง array กับ scalar

In [0]:
a+5

array([[6, 7],
       [8, 9]])

operation ระหว่าง array ที่ dimension ไม่เหมือนกัน - Broadcasting

In [0]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]]); b=np.array([[1,2,3]])
display(a); display(b);

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2, 3]])

In [0]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [0]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]]); b=np.array([[1],[2],[3]])
display(a); display(b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1],
       [2],
       [3]])

In [0]:
a+b

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

**4) Operation สำหรับ matrix (Linear algebra function)**

คูณ matrix

In [0]:
# กำหนด A เป็น matrix ขนาด 3 x 2
A=np.array([[1,2],
            [3,4],
            [5,6]])

# กำหนด B เป็น matrix ขนาด 2 x 1
B=np.array([[1],
            [5]])

In [0]:
# คูณ matrix: A x B =ได้ matrix ผลลัพธ์ขนาด 3 x 1
np.dot(A,B)

array([[11],
       [23],
       [35]])

Transpose

In [0]:
a=np.array([[1,3,2],
           [4,9,6],
           [7,1,3]])
display(a)

array([[1, 3, 2],
       [4, 9, 6],
       [7, 1, 3]])

In [0]:
display(a.T)

array([[1, 4, 7],
       [3, 9, 1],
       [2, 6, 3]])

หา determinant

In [0]:
display(np.linalg.det(a))

-6.999999999999995

หา inverse

In [0]:
display(np.linalg.inv(a))

array([[-3.00000000e+00,  1.00000000e+00, -1.98254112e-16],
       [-4.28571429e+00,  1.57142857e+00, -2.85714286e-01],
       [ 8.42857143e+00, -2.85714286e+00,  4.28571429e-01]])

**5) หาค่าทางสถิติต่างๆ**

In [0]:
a=np.array([[1,3],
           [4,9],
           [7,1]])
display(a)

array([[1, 3],
       [4, 9],
       [7, 1]])

หาค่า min, max, mean, standard dev

In [0]:
print(f'min:{np.min(a)}\tmax:{np.max(a)}\tmean:{np.mean(a)}\tstd:{np.std(a)}')

min:1	max:9	mean:4.166666666666667	std:2.9674156357941426


หาค่า min, max, mean, standard dev แต่ละ column

In [0]:
print(f'min:{np.min(a,axis=0)}\tmax:{np.max(a,axis=0)}\tmean:{np.mean(a,axis=0)}\tstd:{np.std(a,axis=0)}')

min:[1 1]	max:[7 9]	mean:[4.         4.33333333]	std:[2.44948974 3.39934634]


หาค่า min, max, mean, standard dev แต่ละ row

In [0]:
 print(f'min:{np.min(a,axis=1)}\tmax:{np.max(a,axis=1)}\tmean:{np.mean(a,axis=1)}\tstd:{np.std(a,axis=1)}')

min:[1 4 1]	max:[3 9 7]	mean:[2.  6.5 4. ]	std:[1.  2.5 3. ]


**6) Reshape**

In [0]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
display(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
display(a.reshape(9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [0]:
# (1,-1) หมายความว่ากี่ column ก็ได้ ขอให้ 1 row
display(a.reshape(1,-1))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

**7) การสุ่มค่า**

เซตค่า seed เพื่อ random ให้ได้ค่าเดิม

In [0]:
np.random.seed(1)

สร้าง array ที่มีค่า random ค่าระหว่าง (0,1)

In [0]:
display(np.random.rand(3,2))

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02]])

สร้าง array ที่มีค่า random แบบ normal distribution (mean=0, std=1)

In [0]:
display(np.random.randn(3,2))

array([[-0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ],
       [ 1.74481176, -0.7612069 ]])

random ค่าจากใน list โดยกำหนดค่า probabability ของแต่ละตัวได้

In [0]:
display(np.random.choice([3,'nay',7,'yay',11],p=[0.1,0.1,0.2,0.3,0.3]))

'7'